In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option("display.max_rows" , None)
pd.set_option("display.max_columns" , None)

In [4]:
df = pd.read_csv("/content/gurgaon_properties.csv")

In [5]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3804,3 BHK Flat in Nirvana Country,flat,unitech harmony,2.60,9590.0,2711.0,Super Built up area 2711(251.86 sq.m.)Built Up...,3,4,2,"servant room,others","1501, Nirvana Country, Gurgaon, Haryana",15.0,North-East,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'M3M Cosmopo...","Situated in nirvana country, gurgaon, unitech ...","['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
2864,12 Bedroom House for sale in DLF Phase 1,house,independent,10.50,43210.0,2430.0,Plot area 302(252.51 sq.m.)Built Up area: 300 ...,12,12,3+,"servant room,pooja room","Dlf Phase 1, DLF Phase 1, Gurgaon, Haryana",4.0,North-East,1 to 5 Year Old,"['Guru dronacharya metro station', 'Dlf phase ...","Dlf phase 1 very prime location , this buildin...","['1 Water Purifier', '20 Fan', '1 Exhaust Fan'...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3588,3 BHK Flat in Sector 82 Gurgaon,flat,vatika the seven lamps,1.28,6819.0,1877.0,Super Built up area 1877(174.38 sq.m.)Built Up...,3,3,3,study room,"303, Sector 82 Gurgaon, Gurgaon, Haryana",3.0,North,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...",This beautiful 3 bhk flat in sector 82 gurgaon...,"['3 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction5 out of..."
3631,4 Bedroom House for sale in Sohna Gurgaon Road,house,independent,2.00,7479.0,2674.0,Built Up area: 2674 (248.42 sq.m.),4,3,0,not available,"Sohna Gurgaon Road, Sohna Gurgaon Road, Gurgao...",1.0,North,undefined,NaN,4bhk villa for resale in sohna gurgaon road so...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
709,3 BHK Flat in Sector 60 Gurgaon,flat,ireo skyon,2.65,13125.0,2019.0,Super Built up area 2045(189.99 sq.m.)Built Up...,3,4,3+,servant room,"Block D, Sector 60 Gurgaon, Gurgaon, Haryana",7.0,North-East,5 to 10 Year Old,"['Sector 55-56 Metro', 'Golf Course Extension'...",Ireo skyon all sizes available at best price g...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."

In [6]:
df.shape

(3961, 20)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [9]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [14]:
df.insert(loc = 3 , column = 'sector' , value = df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [15]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,Sector 102,0.95,10383.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 6...,2,2,2,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",14.0,NaN,undefined,NaN,Multistorey apartment is available for sale. I...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,Sector 71,0.79,6594.0,1198.0,Super Built up area 1198(111.3 sq.m.),2,2,2,others,"Sector 71 Gurgaon, Gurgaon, Haryana",8.0,South-East,1 to 5 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",We are the proud owners of this 2 bhk apartmen...,"['1 Wardrobe', '1 Fan', '2 Light', '1 TV', '1 ...",NaN,"['Green Area5 out of 5', 'Amenities4 out of 5'..."
2,2 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,Sector 71,0.95,7917.0,1200.0,Built Up area: 1200 (111.48 sq.m.),2,2,0,not available,"Sector 71, Sector 71 Gurgaon, Gurgaon, Haryana",5.0,South,undefined,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Best in class property available at sector 71 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction3 out of..."
3,5 Bedroom House for sale in Jacobpura Near Sad...,house,jacobpura gurugram,Jacobpura Near Sadar Bazar,1.30,23557.0,552.0,Plot area 56.6(47.32 sq.m.),5,2,1,others,"520/8 Jacobpura Gurugram Gali Number 2, Jacobp...",3.0,South-West,10+ Year Old,"['Hanuman Mandir', 'Sharma Hospital Gurgaon', ...","Close to metro station, close to school, close...","['2 Wardrobe', '6 Fan', '20 Light', 'No AC', '...",NaN,NaN
4,3 BHK Flat in Sector 102 Gurgaon,flat,conscient heritage max,Sector 102,2.00,9306.0,2149.0,Super Built up area 2149(199.65 sq.m.)Built Up...,3,4,3+,"study room,servant room","1004, Sector 102 Gurgaon, Gurgaon, Haryana",13.0,North-East,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...",Conscient heritage max is one of gurgaon's mos...,"['5 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."

In [17]:
df['sector'] = df['sector'].str.lower()

In [18]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [19]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [20]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [21]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [24]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [25]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 81                      90
sector 65                      90
sector 90                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 56                      57
sector 95                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 37c                     53
sector 70                      53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 113                     43
sector 25                      43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 57                      24
sector 112                     24
sector 24                      24
sector 14                      23
sector 33                      23
sector 88a                     23
sector 105                     23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 82a                     20
sector 22                      20
sector 3                       20
sector 78                      19
sector 47                      19
sector 74                      18
gwal pahari                    18
sector 63a                     18
sector 91                      17
sector 62                      17
sector 99                      16
sector 110                     16
sector 60                      15
sector 63                      15
sector 1 manesar               14
sector 76                      14
sector 52                      14
sector 55                      14
sector 53                      14
sector 36a                     13
sector 46                      13
sector 9                       13
sector 6                       13
sector 4 phase 2               13
sector 31                      12
sector 38                      12
sector 39                      12
sohna road road                12
sector 93                      12
sector 9a                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 13                      10
sector 1a manesar              10
sector 45                       9
sector 3 phase 2                9
sector 95a                      9
manesar                         9
sector 23                       8
sector 2 extension              8
c block sector 43               8
sector 8                        8
sector 17                       8
sector 40                       8
sector 59                       8
dwarka expressway               8
sector 89 a                     8
sector 10a                      8
sector 58                       7
sector 36 sohna road            7
sector 51                       7
sector 21                       6
sector 5                        6
sector 1                        6
sector 80                       5
sector 23a                      5
new sector 2                    5
sector 30                       5
sector 3a                       4
sector 36                       4
sector 12a                      4
new                             4
sector 17b                      3
sector 73                       3
a block sector 43               3
sector 88b                      3
sector 27                       3
maruti kunj                     3
sector 17a                      3
patel nagar                     3
sector 15                       3
b block sector 43               3
sector 110 a                    3
Name: count, dtype: int64

In [27]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [28]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [29]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
236,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
1110,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
1436,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
2706,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN

In [33]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [34]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
681,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
1213,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2068,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3257,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3467,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [36]:
df.loc[[1072,1486,3040,3875],'sector'] = 'sector 110'

In [37]:
df['sector'] = df['sector'].str.replace('new sector 2','sector 2')

In [38]:
df.shape

(3803, 21)

In [39]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,sector 102,0.95,10383.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 6...,2,2,2,not available,"Sector 102, Sector 102 Gurgaon, Gurgaon, Haryana",14.0,NaN,undefined,NaN,Multistorey apartment is available for sale. I...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,sector 71,0.79,6594.0,1198.0,Super Built up area 1198(111.3 sq.m.),2,2,2,others,"Sector 71 Gurgaon, Gurgaon, Haryana",8.0,South-East,1 to 5 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",We are the proud owners of this 2 bhk apartmen...,"['1 Wardrobe', '1 Fan', '2 Light', '1 TV', '1 ...",NaN,"['Green Area5 out of 5', 'Amenities4 out of 5'..."
2,2 BHK Flat in Sector 71 Gurgaon,flat,chd avenue,sector 71,0.95,7917.0,1200.0,Built Up area: 1200 (111.48 sq.m.),2,2,0,not available,"Sector 71, Sector 71 Gurgaon, Gurgaon, Haryana",5.0,South,undefined,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Best in class property available at sector 71 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction3 out of..."
4,3 BHK Flat in Sector 102 Gurgaon,flat,conscient heritage max,sector 102,2.00,9306.0,2149.0,Super Built up area 2149(199.65 sq.m.)Built Up...,3,4,3+,"study room,servant room","1004, Sector 102 Gurgaon, Gurgaon, Haryana",13.0,North-East,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...",Conscient heritage max is one of gurgaon's mos...,"['5 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
5,4 BHK Flat in Sector 85 Gurgaon,flat,ss the leaf,sector 85,2.13,7574.0,2812.0,Super Built up area 2812(261.24 sq.m.)Built Up...,4,4,3,not available,"Sector 85 Gurgaon, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","This 4 bhk flat is located in ss, which houses...","['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou..."

In [40]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [41]:
df.head()

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
0,flat,shapoorji pallonji joyville gurugram,sector 102,0.95,10383.0,915.0,Built Up area: 915 (85.01 sq.m.)Carpet area: 6...,2,2,2,not available,14.0,NaN,undefined,NaN,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
1,flat,chd avenue,sector 71,0.79,6594.0,1198.0,Super Built up area 1198(111.3 sq.m.),2,2,2,others,8.0,South-East,1 to 5 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...","['1 Wardrobe', '1 Fan', '2 Light', '1 TV', '1 ...",NaN
2,flat,chd avenue,sector 71,0.95,7917.0,1200.0,Built Up area: 1200 (111.48 sq.m.),2,2,0,not available,5.0,South,undefined,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
4,flat,conscient heritage max,sector 102,2.00,9306.0,2149.0,Super Built up area 2149(199.65 sq.m.)Built Up...,3,4,3+,"study room,servant room",13.0,North-East,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...","['5 Fan', '1 Exhaust Fan', '3 Geyser', '1 Stov...","['Centrally Air Conditioned', 'Water purifier'..."
5,flat,ss the leaf,sector 85,2.13,7574.0,2812.0,Super Built up area 2812(261.24 sq.m.)Built Up...,4,4,3,not available,2.0,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F..."

In [42]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [43]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)