In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
df = pd.read_csv("/content/houses.csv")

In [4]:
pd.set_option("display.max_rows" , None)
pd.set_option("display.max_columns",None)
df.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [5]:
df.shape

(1095, 21)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1095 non-null   object
 1   link             1095 non-null   object
 2   society          471 non-null    object
 3   price            968 non-null    object
 4   rate             1054 non-null   object
 5   area             1095 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 179.8+ KB

In [8]:
df.duplicated().sum()

np.int64(13)

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(1082, 21)

In [11]:
df.isnull().sum()

property_name        0
link                 0
society            619
price              127
rate                41
area                 0
areaWithType       108
bedRoom            108
bathroom           108
balcony            108
additionalRoom     504
address             64
noOfFloor          127
facing             420
agePossession      108
nearbyLocations    182
description         59
furnishDetails     350
features           420
rating             188
property_id         59
dtype: int64

In [12]:
# cols to drop -> link , property_id
df.drop(columns=['link' , 'property_id'],inplace = True)

/tmp/ipython-input-12-1241505326.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['link' , 'property_id'],inplace = True)

In [13]:
df.isnull()

      property_name  society  price   rate   area  areaWithType  bedRoom  \
0             False    False  False  False  False         False    False
1             False     True  False  False  False         False    False
2             False     True  False  False  False         False    False
3             False     True  False  False  False         False    False
4             False     True  False  False  False         False    False
5             False     True  False  False  False         False    False
6             False    False  False  False  False         False    False
7             False    False  False  False  False         False    False
8             False     True  False  False  False         False    False
9             False    False  False  False  False         False    False
10            False     True  False  False  False         False    False
11            False     True  False  False  False         False    False
12            False    False  False  False  False         False    False
13            False     True  False  False  False         False    False
14            False     True  False  False  False         False    False
15            False     True  False  False  False         False    False
16            False    False  False  False  False         False    False
17            False     True  False  False  False         False    False
18            False    False  False  False  False         False    False
19            False     True  False  False  False         False    False
20            False     True  False  False  False         False    False
21            False    False  False  False  False         False    False
22            False     True  False  False  False         False    False
23            False    False  False  False  False         False    False
24            False     True  False  False  False         False    False
25            False    False  False  False  False         False    False
26            False    False  False  False  False         False    False
27            False     True  False  False  False         False    False
28            False     True  False  False  False         False    False
29            False     True  False  False  False         False    False
30            False    False  False  False  False         False    False
31            False     True  False  False  False         False    False
32            False     True  False  False  False         False    False
33            False     True  False  False  False         False    False
34            False     True  False  False  False         False    False
35            False     True  False  False  False         False    False
36            False    False  False  False  False         False    False
37            False     True  False  False  False         False    False
38            False    False  False  False  False         False    False
39            False     True  False  False  False         False    False
40            False     True  False  False  False         False    False
41            False    False  False  False  False         False    False
42            False     True  False  False  False         False    False
43            False     True  False  False  False         False    False
44            False     True  False  False  False         False    False
45            False     True  False  False  False         False    False
46            False    False  False  False  False         False    False
47            False    False   True   True  False         False    False
48            False    False  False  False  False         False    False
49            False     True  False  False  False         False    False
50            False     True  False  False  False         False    False
51            False     True  False  False  False         False    False
52            False     True  False  False  False         False    False
53            False    False  False  False  False         False    False
54            False    False  False  False  False         False    False
55            False    False  False  False  False         False    False
56            False    False  False  False  False         False    False
57            False     True  False  False  False         False    False
58            False    False  False  False  False         False    False
59            False    False  False  False  False         False    False
60            False    False   True  False  False          True     True
61            False     True   True  False  False          True     True
62            False     True   True  False  False          True     True
63            False    False   True  False  False          True     True
64            False    False   True  False  False          True     True
65            False     True   True  False  False          True     True
66            False     True   True  False  False          True     True
67            False    False   True  False  False          True     True
68            False    False   True  False  False          True     True
69            False     True   True  False  False          True     True
70            False    False   True   True  False          True     True
71            False     True   True  False  False          True     True
72            False    False   True  False  False          True     True
73            False    False  False  False  False         False    False
74            False     True  False  False  False         False    False
75            False    False   True  False  False          True     True
76            False    False   True  False  False          True     True
77            False     True  False  False  False         False    False
78            False     True  False  False  False         False    False
79            False    False   True  False  False          True     True
80            False    False   True  False  False          True     True
81            False    False   True  False  False          True     True
82            False    False   True  False  False          True     True
83            False    False   True  False  False          True     True
84            False    False   True  False  False          True     True
85            False    False   True  False  False          True     True
86            False    False   True  False  False          True     True
87            False    False   True  False  False          True     True
88            False    False   True  False  False          True     True
89            False    False   True  False  False          True     True
90            False    False   True  False  False          True     True
91            False    False   True  False  False          True     True
92            False     True  False  False  False         False    False
93            False     True  False  False  False         False    False
94            False    False   True  False  False          True     True
95            False    False   True  False  False          True     True
96            False    False   True  False  False          True     True
97            False    False   True  False  False          True     True
98            False    False   True  False  False          True     True
99            False    False   True  False  False          True     True
100           False    False   True  False  False          True     True
101           False    False   True   True  False          True     True
102           False    False   True   True  False          True     True
103           False    False  False  False  False         False    False
104           False    False  False  False  False         False    False
105           False    False   True  False  False          True     True
106           False    False   True  False  False          True     True
107           False    False   True  False  False          True     True
108           False    False   True  False  False          True     True
109           False    False   True  False  False          True     True
110           False    False   True  False  False          True     True
111           False    False   True  False  False          True     True
112           False    False   True  False  False          True     True
113           False    False   True  False  False          True     True
114           False    False  False  False  False         False    False
115           False    False   True  False  False          True     True
116           False    False   True  False  False          True     True
117           False    False   True   True  False          True     True
118           False    False   True   True  False          True     True
119           False     True  False  False  False         False    False
120           False     True  False  False  False         False    False
121           False     True  False  False  False         False    False
122           False    False  False  False  False         False    False
123           False    False   True  False  False          True     True
124           False    False   True  False  False          True     True
125           False     True  False  False  False         False    False
126           False     True  False  False  False         False    False
127           False    False  False  False  False         False    False
128           False    False   True   True  False          True     True
129           False    False  False  False  False         False    False
130           False     True  False  False  False         False    False
131           False     True  False  False  False         False    False
132           False    False  False  False  False         False    False
133           False     True  False  False  False         False    False
134           False     True  False  False  False         False    False
135           False     True  False  False  False         False    False
136           False     True  False  False  False         False    False
137           False     True  False  False  False         False    False
138           False     True  False  False  False         False    False
139           False     True  False  False  False         False    False
140           False    False  False  False  False         False    False
141           False    False  False  False  False         False    False
142           False    False  False  False  False         False    False
143           False    False  False  False  False         False    False
144           False    False  False  False  False         False    False
145           False    False  False  False  False         False    False
146           False    False  False  False  False         False    False
147           False    False  False  False  False         False    False
148           False    False  False  False  False         False    False
149           False    False  False  False  False         False    False
150           False    False  False  False  False         False    False
151           False    False  False  False  False         False    False
152           False    False  False  False  False         False    False
153           False     True  False  False  False         False    False
154           False    False  False  False  False         False    False
155           False    False  False  False  False         False    False
156           False     True  False  False  False         False    False
157           False     True  False  False  False         False    False
158           False     True  False  False  False         False    False
159           False     True  False  False  False         False    False
160           False     True  False  False  False         False    False
161           False     True  False  False  False         False    False
162           False     True  False  False  False         False    False
163           False    False  False  False  False         False    False
164           False    False  False  False  False         False    False
165           False     True  False  False  False         False    False
166           False    False  False  False  False         False    False
167           False     True  False  False  False         False    False
168           False     True  False  False  False         False    False
169           False     True  False  False  False         False    False
170           False     True  False  False  False         False    False
171           False    False  False  False  False         False    False
172           False    False  False  False  False         False    False
173           False    False  False  False  False         False    False
174           False    False  False  False  False         False    False
175           False    False  False  False  False         False    False
176           False    False  False  False  False         False    False
177           False    False  False  False  False         False    False
178           False    False   True  False  False          True     True
179           False    False   True  False  False          True     True
180           False    False   True  False  False          True     True
181           False     True   True  False  False          True     True
182           False    False   True  False  False          True     True
183           False     True   True  False  False          True     True
184           False     True   True  False  False          True     True
185           False     True   True  False  False          True     True
186           False     True   True  False  False          True     True
187           False     True   True  False  False          True     True
188           False    False   True  False  False          True     True
189           False     True   True  False  False          True     True
190           False     True   True  False  False          True     True
191           False     True   True  False  False          True     True
192           False     True   True  False  False          True     True
193           False    False   True  False  False          True     True
194           False     True   True  False  False          True     True
195           False    False   True  False  False          True     True
196           False    False   True  False  False          True     True
197           False     True   True  False  False          True     True
198           False     True   True  False  False          True     True
199           False     True   True  False  False          True     True
200           False     True  False  False  False         False    False
201           False     True  False  False  False         False    False
202           False    False  False  False  False         False    False
203           False     True  False  False  False         False    False
204           False    False  False  False  False         False    False
205           False     True  False  False  False         False    False
206           False     True  False  False  False         False    False
207           False     True  False  False  False         False    False
208           False     True  False  False  False         False    False
209           False    False  False  False  False         False    False
210           False     True  False  False  False         False    False
211           False     True  False  False  False         False    False
212           False     True  False  False  False         False    False
213           False     True  False  False  False         False    False
214           False     True  False  False  False         False    False
215           False     True  False  False  False         False    False
216           False    False  False  False  False         False    False
217           False     True  False  False  False         False    False
218           False     True  False  False  False         False    False
219           False     True  False  False  False         False    False
220           False    False  False  False  False         False    False
221           False     True  False  False  False         False    False
222           False     True  False  False  False         False    False
223           False    False  False  False  False         False    False
224           False     True  False  False  False         False    False
225           False    False  False  False  False         False    False
226           False     True  False  False  False         False    False
227           False     True  False  False  False         False    False
228           False     True  False  False  False         False    False
229           False     True  False  False  False         False    False
230           False     True  False  False  False         False    False
231           False     True  False  False  False         False    False
232           False     True  False  False  False         False    False
233           False     True  False  False  False         False    False
234           False    False  False  False  False         False    False
235           False     True  False  False  False         False    False
236           False     True  False  False  False         False    False
237           False    False  False  False  False         False    False
238           False     True  False  False  False         False    False
239           False    False  False  False  False         False    False
240           False    False  False  False  False         False    False
241           False    False  False  False  False         False    False
242           False    False  False  False  False         False    False
243           False     True  False  False  False         False    False
244           False    False  False  False  False         False    False
245           False     True  False  False  False         False    False
246           False    False  False  False  False         False    False
247           False     True  False  False  False         False    False
248           False    False  False  False  False         False    False
249           False     True  False  False  False         False    False
250           False    False  False  False  False         False    False
251           False     True  False  False  False         False    False
252           False     True  False  False  False         False    False
253           False    False  False  False  False         False    False
254           False     True  False  False  False         False    False
255           False    False  False  False  False         False    False
256           False     True  False  False  False         False    False
257           False     True  False  False  False         False    False
258           False     True  False  False  False         False    False
259           False     True  False  False  False         False    False
260           False     True  False  False  False         False    False
261           False    False  False  False  False         False    False
262           False     True  False  False  False         False    False
263           False     True  False  False  False         False    False
264           False     True  False  False  False         False    False
265           False     True  False  False  False         False    False
266           False     True  False  False  False         False    False
267           False     True  False  False  False         False    False
268           False     True  False  False  False         False    False
269           False     True  False  False  False         False    False
270           False     True  False  False  False         False    False
271           False     True  False  False  False         False    False

In [14]:
df.drop([1091 , 1092 , 1093 , 1094 , 894,371,372,373,358,359,360,361,362,363,364,365,366,367,368,369,353,354,355,356,60,61,62,63,64,65,66,67,68,69,70,71,72,75,76,79,80,81,82,83,84,85,86,87,88,89,90,91,94,95,96,97,98,99,100,101,102,105,106,107,108,109,110,111,112,113,115,116,117,118,123,124,128,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,312,313,319,327,328,329,330,331],inplace=True)

/tmp/ipython-input-14-4173441474.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop([1091 , 1092 , 1093 , 1094 , 894,371,372,373,358,359,360,361,362,363,364,365,366,367,368,369,353,354,355,356,60,61,62,63,64,65,66,67,68,69,70,71,72,75,76,79,80,81,82,83,84,85,86,87,88,89,90,91,94,95,96,97,98,99,100,101,102,105,106,107,108,109,110,111,112,113,115,116,117,118,123,124,128,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,312,313,319,327,328,329,330,331],inplace=True)

In [15]:
df.shape

(975, 19)

In [16]:
df.rename(columns={'rate':"price_per_sqft"},inplace=True)

/tmp/ipython-input-16-85367100.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'rate':"price_per_sqft"},inplace=True)

In [17]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [20]:
# society
df['society'].value_counts()

society
International City by SOBHA Phase 2                  19
Vipul Tatvam Villa                                   19
Emaar MGF Marbella                                   17
International City by Sobha Phase 1                  15
Unitech Uniworld Resorts                             13
Unitech Espace                                       11
DLF City Plots                                       11
DLF City Plots Phase 2                               11
Bptp Visionnaire                                      8
Uppal Southend4.0 ★                                   7
Not Applicable                                        7
Ansals Palam Vihar                                    6
Sushant Lok 1 Builder Floors                          6
Eldeco Mansionz                                       6
DLF City Phase 1                                      5
Unitech Aspen Greens                                  4
Ansal Sushant Lok Plots4.1 ★                          4
nul                                                   4
Vatika India Next4.1 ★                                4
Experion Windchants3.8 ★                              3
Housing Board Colony                                  3
DLF City Plots Phase 3                                3
Sector 14 RWA                                         3
Palam Vihar Extension West Zone RWA                   3
Unitech Nirvana Birch Court                           3
SS Aaron Ville                                        3
Eros Rosewood City4.0 ★                               3
BPTP Astaire Gardens3.7 ★                             3
Ansals Florence Villa                                 3
Eros Rosewood Villas                                  3
Malibu Towne                                          3
DLF New Town Heights 24.0 ★                           3
Vatika Signature Villas                               3
Rattan Garden                                         3
Project Housing Board Colony                          2
Project Mianwali Colony                               2
Emaar The Palm Springs                                2
Nirvana Cedar Crest                                   2
Bhim Garh Kheri                                       2
Sobha City                                            2
Spaze Privy3.9 ★                                      2
shivpuri                                              2
Unitech Deerwood Chase                                2
Suncity Essel Towers4.2 ★                             2
Unitech Escape3.8 ★                                   2
Satya The Hermitage3.5 ★                              2
IFFCO Nagar and 17B RWA                               2
SS Hibiscus                                           2
RWA Sector 46                                         2
Silverglades Tarudhan Valley Golf Resort              2
Tata Primanti4.1 ★                                    2
Suncity Township4.1 ★                                 2
Luxury DLF City Floors                                2
Ansal API Esencia3.7 ★                                2
Bestech Park View Ananda4.2 ★                         2
Sector 38 RWA                                         2
Ardee City3.8 ★                                       2
Hans Enclave                                          2
BPTP Pedestal                                         2
Unitech Palms South City 1                            2
DLF The Arbour                                        1
Om Nagar, Sector-11                                   1
Ansal Heights3.2 ★                                    1
Ninex City                                            1
ATS Tourmaline3.9 ★                                   1
Bhawani enclave                                       1
house number B-34                                     1
Rajendra Park Gurgaon                                 1
Surat nagar phase 2                                   1
DLF Gardencity Enclave                                1
huda sector-56 gurgaon                                1
Sector-17C                                            1
HUDA Ashok Vihar Phase 13.9 ★                         1
Ashok Vihar Phase 3 Gurgaon                           1
private house                                         1
FLOOR WISE DESIGNER KOTHI                             1
DLF New Town Heights3.7 ★                             1
Puri Diplomatic Greens4.0 ★                           1
sector 37                                             1
Grover Homes Sec 4                                    1
My Home                                               1
Signature Global Park4.0 ★                            1
secter 16a daultabad faridabad house no 313           1
Prem Kunj                                             1
Farrukhnagar                                          1
rajendra park sec 105                                 1
ROW HOUSE                                             1
HUDA Plot Sector 38                                   1
Shri Shyam Residency                                  1
mian wali                                             1
Ansal Celebrity Homes                                 1
Krishna Palace                                        1
Huda Flats                                            1
Madan puri                                            1
Sai Kripa Floors 5                                    1
Naman Residency                                       1
Signature Global City 92                              1
DLF City Plot Phase 4                                 1
Bhim Nagar Society                                    1
Vatika Sovereign Next                                 1
Anamika Enclave                                       1
MANOHAR NAGAR                                         1
Anand Garden, Sector-105                              1
RK Excelo                                             1
Anant Raj Estates                                     1
Jacobpura Gurugram                                    1
Smart World Gems                                      1
shree krishna homes                                   1
Hero Homes                                            1
Ganpati Heights Apartment                             1
HUDA Housing Board Colony4.1 ★                        1
Tulip Yellow                                          1
Laxmi Garden Sector-11                                1
bhim nagar, sector 6                                  1
Surendra Homes Dayanand Colony                        1
DLF The Grove                                         1
DLF Garden City Floors                                1
Huda Plots                                            1
Signature Global City 63A                             1
DLF City Plot Phase 3                                 1
Adani Brahma Samsara4.2 ★                             1
sneh vihar                                            1
Sheetla Enclave                                       1
Suncity Avenue 76                                     1
SS Omnia                                              1
Anshul                                                1
Nirmal Enclave, Maruti Kunj Road                      1
Sare Crescent Parc Royal Greens Phase 1               1
Vipul World3.9 ★                                      1
Greenopolis                                           1
jacob pura                                            1
Ansal Esencia Sovereign Floors                        1
Raj Villas                                            1
mahavir pura                                          1
Indiabulls Centrum Park3.7 ★                          1
Jacobpura                                             1
Shivaji Nagar Residential                             1
nirvana country                                       1
Landmark House                                        1
Sector 15 Part 2 RWA                                  1
Central Park Flower Valley Cerise Floors              1
DLF City Plots Phase 4                                1
Birla Navya                                           1
Kothi                                                 1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Nitin Vihar                                           1
rattan vihar rajendra park                            1
Ashok vihar phase III Extension                       1
Ansal                                                 1
Ansal Sushant Residency                               1
DLF Floors Phase 3                                    1
Smart World Orchard                                   1
Unitech South City 23.8 ★                             1
Ansal Florence Super                                  1
Ireo Victory Valley4.1 ★                              1
Ansal API Spanish Court                               1
4S Aradhya Homes                                      1
Emaar Emerald Hills4.1 ★                              1
Vatika The Seven Lamps3.8 ★                           1
Ansal Sushant Lok                                     1
Nirvana Country                                       1
Central Park                                          1
DLF South City 1                                      1
Signature Global City                                 1
Signature Global City 81                              1
Satya The Legend3.8 ★                                 1
Ireo Victory Valley4.0 ★                              1
Independent House Sector 45                           1
DLF Alameda                                           1
Unitech Greenwood City3.6 ★                           1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Central Park Flower Valley                            1
DLF Pink Town House4.0 ★                              1
The Laburnum                                          1
Vatika Independent Floors3.8 ★                        1
Ansal Sushant Lok 2                                   1
Godrej Meridien                                       1
Sector 57 Huda                                        1
Saksham Welfare Association                           1
Huda                                                  1
Huda Floor                                            1
Name: count, dtype: int64

In [21]:
df['society'].value_counts().shape

(182,)

In [22]:
df['society'] = df['society'].apply(lambda name : re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

/tmp/ipython-input-22-344590939.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['society'] = df['society'].apply(lambda name : re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [23]:
df['society'].value_counts().shape

(180,)

In [25]:
df['society'] = df['society'].str.replace("nan",'independent')

/tmp/ipython-input-25-61268524.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['society'] = df['society'].str.replace("nan",'independent')

In [26]:
df['society'].isnull().sum()

np.int64(0)

In [27]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [28]:
# price
df['price'].value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
4.5 Crore           13
5 Crore             13
8 Crore             13
50 Lac              13
75 Lac              13
70 Lac              13
7 Crore             12
8.5 Crore           12
85 Lac              12
1.5 Crore           11
4 Crore             11
90 Lac              10
Price on Request    10
2.25 Crore          10
45 Lac              10
60 Lac              10
10 Crore            10
2.5 Crore           10
9 Crore             10
12 Crore             9
2 Crore              9
80 Lac               9
9.5 Crore            9
1.1 Crore            9
1.7 Crore            9
1 Crore              8
1.6 Crore            8
11 Crore             8
6.75 Crore           8
4.6 Crore            8
3.75 Crore           7
1.2 Crore            7
55 Lac               7
40 Lac               7
1.3 Crore            7
12.5 Crore           7
95 Lac               7
65 Lac               7
1.35 Crore           7
2.1 Crore            7
7.5 Crore            6
6.25 Crore           6
3.25 Crore           6
2.95 Crore           6
10.5 Crore           6
13.5 Crore           6
3.6 Crore            6
2.75 Crore           6
1.45 Crore           6
5.7 Crore            6
4.25 Crore           6
1.15 Crore           6
16 Crore             6
15 Crore             5
3 Crore              5
1.25 Crore           5
5.6 Crore            5
38 Lac               5
4.75 Crore           5
7.25 Crore           5
35 Lac               5
2.8 Crore            5
1.8 Crore            5
18 Crore             4
13 Crore             4
4.35 Crore           4
17 Crore             4
3.3 Crore            4
5.8 Crore            4
9.25 Crore           4
1.4 Crore            4
1.65 Crore           4
3.2 Crore            4
5.75 Crore           4
37 Lac               4
4.7 Crore            4
11.5 Crore           4
6.8 Crore            4
2.4 Crore            4
42 Lac               4
8.25 Crore           4
5.25 Crore           4
20 Crore             3
1.95 Crore           3
4.45 Crore           3
62 Lac               3
5.65 Crore           3
82 Lac               3
2.2 Crore            3
6.95 Crore           3
3.85 Crore           3
1.55 Crore           3
2.3 Crore            3
3.1 Crore            3
1.85 Crore           3
92 Lac               3
5.15 Crore           3
32 Lac               3
34 Lac               3
49 Lac               3
1.16 Crore           3
7.35 Crore           3
2.9 Crore            3
3.4 Crore            3
1.9 Crore            3
4.3 Crore            3
8.4 Crore            3
7.2 Crore            3
19 Crore             3
6.4 Crore            3
11.95 Crore          2
1.05 Crore           2
14 Crore             2
11.25 Crore          2
6.3 Crore            2
30 Lac               2
10.45 Crore          2
66 Lac               2
36 Lac               2
26 Crore             2
11.75 Crore          2
8.49 Crore           2
2.55 Crore           2
3.55 Crore           2
3.15 Crore           2
9.9 Crore            2
15.5 Crore           2
58.25 Lac            2
2.15 Crore           2
67 Lac               2
3.05 Crore           2
1.75 Crore           2
48 Lac               2
10.85 Crore          2
7.1 Crore            2
58 Lac               2
4.95 Crore           2
19.5 Crore           2
3.65 Crore           2
10.55 Crore          2
3.35 Crore           2
89 Lac               2
3.51 Crore           2
6.6 Crore            1
6.2 Crore            1
5.9 Crore            1
8.8 Crore            1
1.87 Crore           1
4.12 Crore           1
5.35 Crore           1
5.85 Crore           1
7.05 Crore           1
2.68 Crore           1
2.7 Crore            1
10.75 Crore          1
61 Lac               1
18.25 Crore          1
2.35 Crore           1
8.6 Crore            1
9.55 Crore           1
9.8 Crore            1
4.99 Crore           1
9.85 Crore           1
1.18 Crore           1
9.01 Crore           1
15.1 Crore           1
1.04 Crore           1
25 Crore             1
8.7 Crore            1
15.5 Lac             1
12.39 Crore          1
7.49 Crore           1
55.11 Lac            1
68 Lac               1
4.65 Crore           1
6.1 Crore            1
1.72 Crore           1
52 Lac               1
78 Lac               1
1.52 Crore           1
2.58 Crore           1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
7.69 Crore           1
22 Lac               1
7.5 Lac              1
3.12 Crore           1
11.3 Crore           1
3.69 Crore           1
4.02 Crore           1
3.93 Crore           1
29 Lac               1
3.08 Crore           1
18 Lac               1
24 Lac               1
98 Lac               1
83 Lac               1
7.99 Crore           1
5.4 Crore            1
65.8 Lac             1
18.02 Crore          1
96 Lac               1
13 Lac               1
69 Lac               1
2.43 Crore           1
74 Lac               1
3.09 Crore           1
44 Lac               1
47.5 Lac             1
59 Lac               1
1.39 Crore           1
3.87 Crore           1
2.6 Crore            1
1.34 Crore           1
46 Lac               1
9.54 Crore           1
14.75 Crore          1
8.1 Crore            1
27 Lac               1
24 Crore             1
7.46 Crore           1
17.3 Crore           1
18.9 Crore           1
47 Lac               1
71 Lac               1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
1.07 Crore           1
5.2 Crore            1
42.75 Lac            1
22 Crore             1
4.15 Crore           1
8.9 Crore            1
4.49 Crore           1
8.81 Crore           1
6.81 Crore           1
59.95 Lac            1
3.99 Crore           1
18.5 Crore           1
27.5 Crore           1
8.31 Crore           1
6.21 Crore           1
1.83 Crore           1
5.1 Crore            1
5.46 Crore           1
10.56 Crore          1
2.01 Crore           1
3.9 Crore            1
5.88 Crore           1
52.75 Lac            1
12.25 Crore          1
46.75 Lac            1
9.4 Crore            1
10.3 Crore           1
8.45 Crore           1
6.15 Crore           1
2.47 Crore           1
3.7 Crore            1
18.4 Crore           1
4.4 Crore            1
7.3 Crore            1
7.6 Crore            1
2.65 Crore           1
99 Lac               1
11.29 Crore          1
1.27 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
4.31 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
5.51 Crore           1
23 Crore             1
2.45 Crore           1
7.85 Crore           1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
2.98 Crore           1
Name: count, dtype: int64

In [29]:
df = df[df['price']!='Price on Request']

In [30]:
def treat_price(x) :
  if type(x) == float :
    return x
  else :
    if x[1] == 'Lac':
      return round(float(x[0])/100 , 2)
    else:
      return round(float(x[0]),2)

In [33]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [34]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [35]:
# price_per_sqft
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 22,222/sq.ft.     13
₹ 33,333/sq.ft.     11
₹ 11,111/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 26,667/sq.ft.      6
₹ 37,037/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 30,556/sq.ft.      6
₹ 5,000/sq.ft.       5
₹ 9,444/sq.ft.       5
₹ 8,889/sq.ft.       5
₹ 23,148/sq.ft.      5
₹ 23,333/sq.ft.      5
₹ 8,000/sq.ft.       5
₹ 24,691/sq.ft.      4
₹ 13,333/sq.ft.      4
₹ 9,722/sq.ft.       4
₹ 27,778/sq.ft.      4
₹ 34,722/sq.ft.      4
₹ 35,000/sq.ft.      4
₹ 21,605/sq.ft.      4
₹ 18,889/sq.ft.      4
₹ 32,407/sq.ft.      4
₹ 25,000/sq.ft.      3
₹ 50,000/sq.ft.      3
₹ 12,000/sq.ft.      3
₹ 11,250/sq.ft.      3
₹ 20,000/sq.ft.      3
₹ 15,625/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 6,944/sq.ft.       3
₹ 13,889/sq.ft.      3
₹ 32,222/sq.ft.      3
₹ 10,556/sq.ft.      3
₹ 12,222/sq.ft.      3
₹ 60,000/sq.ft.      3
₹ 8,235/sq.ft.       3
₹ 25,926/sq.ft.      3
₹ 29,880/sq.ft.      3
₹ 33,951/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 14,815/sq.ft.      3
₹ 15,555/sq.ft.      3
₹ 36,111/sq.ft.      3
₹ 9,000/sq.ft.       2
₹ 38,194/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 100,000/sq.ft.     2
₹ 8,888/sq.ft.       2
₹ 6,666/sq.ft.       2
₹ 12,500/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 11,574/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 4,444/sq.ft.       2
₹ 7,407/sq.ft.       2
₹ 17,778/sq.ft.      2
₹ 29,630/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 35,185/sq.ft.      2
₹ 17,037/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 35,556/sq.ft.      2
₹ 12,342/sq.ft.      2
₹ 15,257/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 45,833/sq.ft.      2
₹ 7,500/sq.ft.       2
₹ 44,444/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 23,457/sq.ft.      2
₹ 20,635/sq.ft.      2
₹ 24,155/sq.ft.      2
₹ 24,306/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 75,000/sq.ft.      2
₹ 21,759/sq.ft.      2
₹ 10,753/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 3,857/sq.ft.       2
₹ 37,627/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 11,852/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 24,500/sq.ft.      2
₹ 12,963/sq.ft.      2
₹ 7,058/sq.ft.       2
₹ 14,444/sq.ft.      2
₹ 38,760/sq.ft.      2
₹ 24,845/sq.ft.      2
₹ 17,284/sq.ft.      2
₹ 10,101/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 9,634/sq.ft.       2
₹ 21,124/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 48,148/sq.ft.      2
₹ 25,562/sq.ft.      2
₹ 38,095/sq.ft.      2
₹ 18,888/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 13,501/sq.ft.      1
₹ 20,988/sq.ft.      1
₹ 400,000/sq.ft.     1
₹ 21,296/sq.ft.      1
₹ 18,626/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 26,298/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 27,191/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 241,666/sq.ft.     1
₹ 34,491/sq.ft.      1
₹ 33,592/sq.ft.      1
₹ 24,455/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 20,741/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 42,054/sq.ft.      1
₹ 1,560/sq.ft.       1
₹ 13,178/sq.ft.      1
₹ 18,444/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 27,222/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 23,932/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 32,253/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 19,360/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 23,437/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 29,697/sq.ft.      1
₹ 47,803/sq.ft.      1
₹ 22,812/sq.ft.      1
₹ 261,194/sq.ft.     1
₹ 178,571/sq.ft.     1
₹ 27,461/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 17,662/sq.ft.      1
₹ 39,062/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 20,068/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 21,242/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 10,484/sq.ft.      1
₹ 160,000/sq.ft.     1
₹ 8,127/sq.ft.       1
₹ 7,555/sq.ft.       1
₹ 49,500/sq.ft.      1
₹ 13,030/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 10,610/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 8,155/sq.ft.       1
₹ 10,591/sq.ft.      1
₹ 24,074/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 5,160/sq.ft.       1
₹ 144,444/sq.ft.     1
₹ 9,615/sq.ft.       1
₹ 6,813/sq.ft.       1
₹ 15,046/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 84,000/sq.ft.      1
₹ 6,938/sq.ft.       1
₹ 266,666/sq.ft.     1
₹ 7,539/sq.ft.       1
₹ 10,067/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 28,787/sq.ft.      1
₹ 28,898/sq.ft.      1
₹ 28,200/sq.ft.      1
₹ 18,658/sq.ft.      1
₹ 20,026/sq.ft.      1
₹ 20,444/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 6,289/sq.ft.       1
₹ 17,857/sq.ft.      1
₹ 7,000/sq.ft.       1
₹ 14,166/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 7,777/sq.ft.       1
₹ 7,168/sq.ft.       1
₹ 33,665/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 44,265/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 38,734/sq.ft.      1
₹ 23,442/sq.ft.      1
₹ 41,833/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 11,583/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 31,915/sq.ft.      1
₹ 11,102/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 36,911/sq.ft.      1
₹ 2,716/sq.ft.       1
₹ 6,230/sq.ft.       1
₹ 11,240/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 23,889/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 10,085/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 20,349/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 10,740/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 19,737/sq.ft.      1
₹ 5,093/sq.ft.       1
₹ 34,307/sq.ft.      1
₹ 7,007/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 20,566/sq.ft.      1
₹ 35,294/sq.ft.      1
₹ 8,254/sq.ft.       1
₹ 5,128/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 15,926/sq.ft.      1
₹ 14,285/sq.ft.      1
₹ 25,463/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 12,393/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 18,620/sq.ft.      1
₹ 17,014/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 7,172/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 8,137/sq.ft.       1
₹ 7,582/sq.ft.       1
₹ 18,605/sq.ft.      1
₹ 29,333/sq.ft.      1
₹ 16,066/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 7,750/sq.ft.       1
₹ 47,167/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 20,197/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 25,556/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 21,825/sq.ft.      1
₹ 16,577/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 19,231/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 14,667/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 41,315/sq.ft.      1
₹ 3,786/sq.ft.       1
₹ 9,349/sq.ft.       1
₹ 21,251/sq.ft.      1
₹ 23,504/sq.ft.      1
₹ 234,375/sq.ft.     1
₹ 15,432/sq.ft.      1
₹ 21,786/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 31,666/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 18,008/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 20,599/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 21,367/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 10,579/sq.ft.      1
₹ 42,194/sq.ft.      1
₹ 15,278/sq.ft.      1
₹ 201,388/sq.ft.     1
₹ 17,187/sq.ft.      1
₹ 26,502/sq.ft.      1
₹ 38,251/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 19,608/sq.ft.      1
₹ 8,089/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 19,607/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 18,928/sq.ft.      1
₹ 40,850/sq.ft.      1
₹ 24,390/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 31,790/sq.ft.      1
₹ 29,293/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 1,859/sq.ft.       1
₹ 12,037/sq.ft.      1
₹ 30,864/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 19,847/sq.ft.      1
₹ 16,056/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 7,718/sq.ft.       1
₹ 25,535/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 7,870/sq.ft.       1
₹ 28,233/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 19,820/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 36,883/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 14,222/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 19,125/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 16,666/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 15,000/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 23,556/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 16,975/sq.ft.      1
₹ 62,222/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 7,827/sq.ft.       1
₹ 12,592/sq.ft.      1
₹ 15,384/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 29,336/sq.ft.      1
₹ 10,288/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 10,277/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 12,551/sq.ft.      1
₹ 557/sq.ft.         1
₹ 8,947/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 230,547/sq.ft.     1
₹ 8,411/sq.ft.       1
₹ 32,291/sq.ft.      1
₹ 41,666/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 10,555/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 138,888/sq.ft.     1
₹ 7,666/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 7,778/sq.ft.       1
₹ 40,775/sq.ft.      1
₹ 99,173/sq.ft.      1
₹ 6,172/sq.ft.       1
₹ 7,589/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 4,117/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 8,701/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 8,486/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 9,111/sq.ft.       1
₹ 20,359/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 53,125/sq.ft.      1
₹ 17,900/sq.ft.      1
₹ 39,886/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 40,909/sq.ft.      1
₹ 27,155/sq.ft.      1
₹ 90,000/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 13,157/sq.ft.      1
₹ 5,888/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 9,654/sq.ft.       1
₹ 4,808/sq.ft.       1
₹ 8,222/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 7,627/sq.ft.       1
₹ 14,492/sq.ft.      1
₹ 10,089/sq.ft.      1
₹ 8,697/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 9,333/sq.ft.       1
₹ 21,667/sq.ft.      1
₹ 20,425/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 57,692/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 17,695/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,817/sq.ft.      1
₹ 2/sq.ft.           1
₹ 6,173/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 25,386/sq.ft.      1
₹ 28,490/sq.ft.      1
₹ 122,222/sq.ft.     1
₹ 13,542/sq.ft.      1
₹ 19,097/sq.ft.      1
₹ 7,290/sq.ft.       1
₹ 27,741/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 20,690/sq.ft.      1
₹ 28,283/sq.ft.      1
₹ 16,378/sq.ft.      1
₹ 37,777/sq.ft.      1
₹ 12,519/sq.ft.      1
₹ 27,971/sq.ft.      1
₹ 21,000/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 40,135/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 29,716/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 23,240/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 33,129/sq.ft.      1
₹ 20,115/sq.ft.      1
₹ 105,751/sq.ft.     1
₹ 38,150/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 43,066/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 13,410/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 46,906/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 28,424/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 41,615/sq.ft.      1
₹ 25,111/sq.ft.      1
₹ 7,309/sq.ft.       1
₹ 74,074/sq.ft.      1
₹ 10,233/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,928/sq.ft.       1
₹ 8,007/sq.ft.       1
₹ 5,698/sq.ft.       1
₹ 14,729/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 16,428/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 86,567/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 17,650/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 26,423/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 9,028/sq.ft.       1
₹ 4,074/sq.ft.       1
₹ 630/sq.ft.         1
₹ 38,667/sq.ft.      1
₹ 19,753/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 63,492/sq.ft.      1
₹ 2,500/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 3,704/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 5,666/sq.ft.       1
₹ 20,062/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 25,543/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 17,500/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 14,323/sq.ft.      1
₹ 4,222/sq.ft.       1
₹ 20,233/sq.ft.      1
₹ 8,012/sq.ft.       1
₹ 183,333/sq.ft.     1
₹ 10,142/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 14,583/sq.ft.      1
₹ 11,538/sq.ft.      1
₹ 8,730/sq.ft.       1
₹ 8,230/sq.ft.       1
₹ 13,095/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 30,384/sq.ft.      1
₹ 19,818/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 7,619/sq.ft.       1
₹ 98,214/sq.ft.      1
₹ 13,499/sq.ft.      1
₹ 7,820/sq.ft.       1
₹ 4,000/sq.ft.       1
₹ 14,720/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 7,479/sq.ft.       1
₹ 7,400/sq.ft.       1
₹ 16,003/sq.ft.      1
₹ 9,103/sq.ft.       1
₹ 7,727/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 8,702/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 26,973/sq.ft.      1
₹ 181,818/sq.ft.     1
₹ 6,000/sq.ft.       1
₹ 14,890/sq.ft.      1
₹ 9,210/sq.ft.       1
₹ 6,800/sq.ft.       1
₹ 7,333/sq.ft.       1
₹ 8,101/sq.ft.       1
₹ 14,184/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 13,750/sq.ft.      1
₹ 26,620/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 3,254/sq.ft.       1
₹ 5,333/sq.ft.       1
₹ 4,583/sq.ft.       1
₹ 21,875/sq.ft.      1
₹ 16,667/sq.ft.      1
₹ 7,075/sq.ft.       1
₹ 4,877/sq.ft.       1
₹ 4,251/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 5,397/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 5,583/sq.ft.       1
₹ 3,519/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 6,981/sq.ft.       1
₹ 6,702/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 8,078/sq.ft.       1
₹ 26,570/sq.ft.      1
₹ 6,410/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 5,778/sq.ft.       1
₹ 6,111/sq.ft.       1
₹ 78,125/sq.ft.      1
₹ 17,955/sq.ft.      1
₹ 7,916/sq.ft.       1
₹ 211,111/sq.ft.     1
₹ 7,111/sq.ft.       1
₹ 120,000/sq.ft.     1
₹ 22,297/sq.ft.      1
₹ 125,000/sq.ft.     1
₹ 73,333/sq.ft.      1
₹ 6,790/sq.ft.       1
₹ 315,789/sq.ft.     1
₹ 10,224/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 74,000/sq.ft.      1
₹ 80,000/sq.ft.      1
₹ 6,567/sq.ft.       1
₹ 22,068/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 28,674/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 21,111/sq.ft.      1
₹ 10,784/sq.ft.      1
₹ 12,162/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 22,634/sq.ft.      1
₹ 8,796/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 5,658/sq.ft.       1
₹ 24,545/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 14,072/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 19,869/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 31,506/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 12,400/sq.ft.      1
₹ 232/sq.ft.         1
₹ 218,750/sq.ft.     1
₹ 54,794/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 37,313/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 10,122/sq.ft.      1
₹ 8,642/sq.ft.       1
₹ 6,481/sq.ft.       1
₹ 6,707/sq.ft.       1
₹ 245,398/sq.ft.     1
₹ 11,904/sq.ft.      1
₹ 9,135/sq.ft.       1
₹ 6,367/sq.ft.       1
₹ 23,662/sq.ft.      1
₹ 17,574/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 23,557/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 21,195/sq.ft.      1
₹ 151/sq.ft.         1
₹ 25,103/sq.ft.      1
₹ 14,954/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 6,500/sq.ft.       1
₹ 35,494/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 11,718/sq.ft.      1
₹ 11,555/sq.ft.      1
₹ 3,874/sq.ft.       1
₹ 7,576/sq.ft.       1
₹ 11,556/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 8,784/sq.ft.       1
Name: count, dtype: int64

In [40]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [41]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [42]:
# bedroom
df['bedRoom'].value_counts()

bedRoom
4 Bedrooms     232
5 Bedrooms     194
3 Bedrooms     146
2 Bedrooms      88
6 Bedrooms      81
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      31
12 Bedrooms     28
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
11 Bedrooms      2
19 Bedrooms      2
18 Bedrooms      2
21 Bedrooms      1
20 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: count, dtype: int64

In [45]:
df = df[~df['bedRoom'].isnull()]

In [46]:
df.shape

(964, 19)

In [49]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [50]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [51]:
# bathroom
df['bathroom'].value_counts()

bathroom
4 Bathrooms     228
3 Bathrooms     165
5 Bathrooms     137
2 Bathrooms     114
6 Bathrooms      82
1 Bathroom       65
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      28
12 Bathrooms     22
10 Bathrooms     11
16 Bathrooms      8
13 Bathrooms      4
18 Bathrooms      4
11 Bathrooms      4
17 Bathrooms      3
20 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
34 Bathrooms      1
36 Bathrooms      1
Name: count, dtype: int64

In [55]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [56]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [57]:
# balcony
df['balcony'].value_counts()

balcony
3+ Balconies    365
2 Balconies     220
3 Balconies     159
No Balcony      115
1 Balcony       105
Name: count, dtype: int64

In [58]:
df['balcony'].isnull().sum()

np.int64(0)

In [62]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [63]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [65]:
# additional room
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Others                                11
Pooja Room,Store Room                            11
Servant Room,Others                               8
Pooja Room,Store Room,Study Room,Servant Room     8
Servant Room,Pooja Room                           8
Pooja Room,Servant Room,Store Room                7
Servant Room,Pooja Room,Store Room                6
Store Room,Servant Room                           6
Study Room,Servant Room,Pooja Room,Store Room     6
Study Room,Pooja Room,Servant Room                5
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Servant Room,Store Room                4
Store Room,Pooja Room                             4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Servant Room,Store Room,Pooja Room                4
Pooja Room,Study Room,Others                      4
Pooja Room,Study Room,Store Room                  3
Study Room,Others                                 3
Study Room,Servant Room,Pooja Room                3
Study Room,Pooja Room,Servant Room,Store Room     3
Store Room,Pooja Room,Servant Room                2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Pooja Room,Store Room                  2
Store Room,Pooja Room,Study Room                  2
Servant Room,Study Room,Pooja Room                2
Study Room,Pooja Room,Store Room,Servant Room     2
Study Room,Pooja Room                             2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Servant Room,Study Room,Store Room,Pooja Room     1
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: count, dtype: int64

In [67]:
df['additionalRoom'].fillna("not available",inplace = True)

In [68]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [69]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [70]:
# floor
df['noOfFloor'].value_counts()

noOfFloor
3 Floors     304
2 Floors     288
1 Floors     181
4 Floors     136
5 Floors       9
0 Floors       6
14 Floors      3
6 Floors       3
10 Floors      2
11 Floors      2
12 Floors      2
21 Floors      1
13 Floors      1
27 Floors      1
02 Floors      1
20 Floors      1
41 Floors      1
51 Floors      1
16 Floors      1
33 Floors      1
Name: count, dtype: int64

In [71]:
df[df['noOfFloor'].isnull()]

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
23,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,2,"pooja room,servant room,store room","Sector 48 Gurgaon, Gurgaon, Haryana",NaN,East,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Three side open villa in tatvam villa sector-4...,"['1 Chimney', '1 Modular Kitchen', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
51,8 Bedroom House for sale in Palam Vihar,independent,5.60,17284.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),8,6,3+,"pooja room,study room,servant room,store room","Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
203,3 Bedroom House for sale in DLF Phase 3,independent,1.45,26852.0,(50 sq.m.) Plot Area,Plot area 60(50.17 sq.m.),3,3,1,not available,"DLF Phase 3, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",Interested to sell independent house/villa.Pla...,NaN,['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle5 out of 5..."
252,3 Bedroom House for sale in Ashok Vihar,independent,1.50,10288.0,(135 sq.m.) Plot Area,Plot area 162(135.45 sq.m.)Built Up area: 210 ...,3,3,0,not available,"800 Lane 8 Ashok Vihar Part 1, Ashok Vihar, Gu...",NaN,NaN,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Ground floor and partial first floor built up,[],NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
270,2 Bedroom House for sale in Laxman Vihar Phase 2,independent,4.12,8889.0,(431 sq.m.) Plot Area,Plot area 515(430.61 sq.m.),2,1,3+,not available,"Laxman Vihar Phase 2, Gurgaon, Haryana",NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Shre...","Property next to dhanwapur underpass, which is...",[],NaN,NaN
281,3 Bedroom House for sale in New Palam Vihar Ph...,independent,2.50,5472.0,(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),3,2,1,not available,"B-245, New Palam Vihar Phase 2, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",100 mtr from dwarka express way. On 40ft road,NaN,['Park'],NaN
374,4 Bedroom House for sale in Laxman Vihar,independent,0.65,11111.0,(54 sq.m.) Plot Area,Plot area 65(54.35 sq.m.),4,2,2,not available,"Laxman Vihar, Gurgaon, Haryana",NaN,NaN,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Well maintained two storeyed independent house...,"['1 Wardrobe', '1 Exhaust Fan', '10 Light', '1...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
397,1 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok plots,3.30,26570.0,(115 sq.m.) Plot Area,Plot area 138(115.39 sq.m.),1,1,0,not available,"Sushant Lok Phase 1, Gurgaon, Haryana",NaN,NaN,By 2027,"['Iffco chowk metro station', 'Huda city centr...","Close proximity to gold souk , huda city centr...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
417,2 Bedroom House for sale in Bhawani Enclave,independent,1.10,73333.0,(14 sq.m.) Plot Area,Plot area 150(13.94 sq.m.),2,2,1,others,"Bhawani Enclave, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['State bank ATM', 'Shri Multispeciality Hospi...","2 side open, 1 drawing room, 1 shop, 1 small r...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,NaN
560,2 Bedroom House for sale in Jacobpura,jacob pura,0.35,9722.0,(33 sq.m.) Built-up Area,Built Up area: 360 (33.45 sq.m.),2,1,0,not available,"15/3, Jacobpura, Jacobpura, Gurgaon, Haryana",NaN,NaN,10+ Year Old,NaN,Independece house for sale in jacobpura near k...,[],NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
594,6 Bedroom House for sale in DLF Phase 2,independent,13.00,45710.0,(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),6,8,3+,"pooja room,servant room,study room,store room","DLF Phase 2, Gurgaon, Haryana",NaN,NaN,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Esic...",An impeccable opportunity is here for those wh...,"['1 Water Purifier', '1 Fridge', '1 Sofa', '1 ...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
666,3 Bedroom House for sale in New Colony,independent,6.50,15046.0,(401 sq.m.) Plot Area,Plot area 480(401.34 sq.m.),3,2,3+,not available,"New Colony, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",Old construction house in new colony gurgaon.,[],['Private Garden / Terrace'],"['Environment4 out of 5', 'Lifestyle4 out of 5..."
709,12 Bedroom House for sale in Sector 46 Gurgaon,independent,6.81,36911.0,(171 sq.m.) Plot Area,Plot area 205(171.41 sq.m.),12,14,3+,"servant room,others","Sector 46 Gurgaon, Gurgaon, Haryana",NaN,East,0 to 1 Year Old,"['Axis bank ATM', 'State bank of india ATM', '...",204 sqyds newly floor wise building with basem...,"['14 Wardrobe', '15 Fan', '1 Exhaust Fan', '13...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
832,4 Bedroom House for sale in Sector 86 Gurgaon,dlf new town heights,2.47,7718.0,(297 sq.m.) Plot Area,Plot area 3200(297.29 sq.m.)Built Up area: 280...,4,4,3+,"pooja room,servant room","Sector 86 Gurgaon, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",This is beautiful 4 bhk villa in dlf new town ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
855,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,8.50,26235.0,(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4,4,1,not available,"4 Bed And 4 Bathroom, Sector 48 Gurgaon, Gurga...",NaN,NaN,1 to 5 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",360 sq yard 4 bhk residential villa for sale i...,"['4 Bed', '4 Fan', '1 Exhaust Fan', '4 Light',...","['Maintenance Staff', 'Water Storage', 'Separa...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
862,4 Bedroom House for sale in Sushant Lok Phase 1,ansal sushant lok,10.50,27911.0,(350 sq.m.) Plot Area,Plot area 418(349.5 sq.m.),4,4,2,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",NaN,North-East,10+ Year Old,"['Huda city centre metro station', 'New Life C...",Ansal villa for sale 418 sqyd in d block gated...,"['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
865,4 Bedroom House for sale in Sector 26 Gurgaon,independent,4.60,12198.0,(350 sq.m.) Plot Area,Plot area 419(350.34 sq.m.),4,4,3+,not available,"F-5/10, Sector 26 Gurgaon, Gurgaon, Haryana",NaN,NaN,10+ Year Old,"['Dlf phase 1 metro station', 'Sikandarpur met...",On the lookout for a spacious house in gurgaon...,[],"['Maintenance Staff', 'Park', 'Visitor Parking...",NaN
1003,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,9.00,21251.0,(521 sq.m.) Plot Area,Plot area 5605(520.72 sq.m.)Built Up area: 520...,4,4,3+,"pooja room,servant room,store room","Sector 66 Gurgaon, Gurgaon, Haryana",NaN,South-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",A lifestyle designed to satiate all your sense...,"['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment3 out of 5', 'Safety4 out of 5', ..."
1016,12 Bedroom House for sale in Uppals Southend,uppal southend,6.75,290948.0,(22 sq.m.) Plot Area,Plot area 232(21.55 sq.m.),12,12,3+,"pooja room,study room,servant room,others","Uppals Southend, Gurgaon, Haryana",NaN,West,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address... Uppal southend sector 49 s block si...,"['22 Wardrobe', '24 Fan', '1 Exhaust Fan', '33...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety5 out of 5', ..."

In [74]:
df['noOfFloor'] = df['noOfFloor'].str.split(' ').str.get(0)

In [75]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [76]:
df.rename(columns={'noOfFloor':'floorNum'},inplace = True)

In [77]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115.0,(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,105751.0,(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,38251.0,(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,43066.0,(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,53763.0,(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [78]:
# facing
df['facing'].fillna('NA',inplace = True)

/tmp/ipython-input-78-3821684502.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace = True)

In [79]:
df['area'] = round((df['price']*10000000)/df['price_per_sqft'])

In [80]:
df.insert(loc=1 , column = 'property_type' , value = 'house')

In [81]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [82]:
df.shape

(964, 20)

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 964 entries, 0 to 1090
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    object
 1   property_type    964 non-null    object
 2   society          964 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     964 non-null    object
 7   bedRoom          964 non-null    int64
 8   bathroom         964 non-null    int64
 9   balcony          964 non-null    object
 10  additionalRoom   964 non-null    object
 11  address          959 non-null    object
 12  floorNum         945 non-null    object
 13  facing           964 non-null    object
 14  agePossession    964 non-null    object
 15  nearbyLocations  848 non-null    object
 16  description      964 non-null    object
 17  furnishDetails   729 non-null    object
 18  features         662 non-null    object
 19  rating           843 non-null    object
dtypes: float64(3), int64(2), object(15)
memory usage: 158.2+ KB

In [84]:
df.to_csv("house_cleaned.csv" , index = False)